name: Docker Image CI

on:
  release:
    types: ["published"]
    tags: ["v*"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@master

      # Install applicaion dependencies
      - name: Install dependencies
        run: |
          npm install

      # Build the app
      - name: Build app
        # Ignore linter warnings (https://github.com/orgs/community/discussions/25228)
        env:
          CI: ""
        run: |
          npm run build
          docker build . --file docker/Dockerfile --tag vectara/vectara-answer:$(date +%s)

      - uses: actions/upload-artifact@master
        with:
          name: build_dir
          path: build

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - uses: actions/download-artifact@master
        with:
          name: build_dir
          path: build

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: vectara/vectara-answer

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
